### ISSUE TITLE
Establish Project Milestones, Schedule and Deliverables

### ISSUE THREAD

**Issue by tonypioneer** [tonypioneer/Trust-Indicator#5]
## Description
Establish project milestones, schedule and deliverables for Semester 2 of 2023.
## Why
Project management.

## Closing Criteria
- [x] Complete the establishment of project milestones.
- [x] Complete the establishment of project schedule.
- [x] Complete the establishment of project deliverables.

**Comment by tonypioneer** [comment]
Completed in Week 3. Can be closed.
